export const UPDATE_GAME_RECORD = 'UPDATE_GAME_RECORD';
export const RESTART_GAME = 'RESTART_GAME';
export const PLACE_ONE_PIECE = 'PLACE_ONE_PIECE';
export const RESET_SETUP = 'RESET_SETUP';
export const CHANGE_PLAYERS = 'CHANGE_PLAYERS';
export const CHANGE_RULES = 'CHANGE_RULES';
